In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [85]:
# Importo librerias de Scikit Learn
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression , Ridge
from sklearn.svm import SVR, LinearSVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn import neighbors

from sklearn.model_selection import GridSearchCV

In [3]:
pwd

'/Users/TobiasHara/Desktop/UTN/6to Año/Ciencia de datos/Clase 7'

In [4]:
ls

ML_Strategy_Práctica.ipynb
X_test.csv
Xy_train.csv
clusterai_2020_clase07_clustering_asignacion_properati.ipynb
clusterai_2020_clase07_clustering_credit.ipynb
clusterai_2020_clase07_clustering_vinos.ipynb
clusterai_2020_clase07_dataset_credit.csv
clusterai_2020_clase07_dataset_properati_caba.csv
clusterai_2020_clase07_presentacion.pdf
wine.data
wine.names


In [5]:
# importo datasets
Xy_train = pd.read_csv('/Users/TobiasHara/Desktop/UTN/6to Año/Ciencia de datos/Clase 7/Xy_train.csv')
X_test = pd.read_csv('/Users/TobiasHara/Desktop/UTN/6to Año/Ciencia de datos/Clase 7/X_test.csv')

In [6]:
Xy_train

X          y
0   2.273360   6.054685
1   3.167583   4.581428
2   7.973655   5.392507
3   6.762547   3.108068
4   3.911096   4.225744
..       ...        ...
95  3.787495   5.133706
96  2.759471   4.308327
97  9.661041  11.923565
98  0.582026   1.335725
99  4.087339   5.641851

[100 rows x 2 columns]

In [7]:
np.shape(X_test)

(20, 1)

In [8]:
xtrain = Xy_train.iloc[:,:-1].values
ytrain = Xy_train.iloc[:,1].values
print(xtrain.shape,ytrain.shape)

(100, 1) (100,)


In [12]:
#auto scaling train set
scaler = preprocessing.StandardScaler().fit(xtrain)scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
xtrain_scal = scaler.transform(xtrain) 
xtest_scal = scaler.transform(X_test)

# Linear regression

In [176]:
#Estimador
est = LinearRegression()
parameters = {'fit_intercept' : [False, True]}
n_folds = 5

gs = GridSearchCV(est, param_grid=parameters, cv=n_folds, refit=True, scoring="neg_mean_squared_error")

In [16]:
#Entrenar
gs.fit(xtrain_scal, ytrain)

GridSearchCV(cv=5, error_score=nan,
             estimator=LinearRegression(copy_X=True, fit_intercept=True,
                                        n_jobs=None, normalize=False),
             iid='deprecated', n_jobs=None,
             param_grid={'fit_intercept': [False, True]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=0)

In [17]:
print(gs.best_estimator_, "\n")
print(gs.best_params_, "\n")
print(gs.best_score_, "\n")

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False) 

{'fit_intercept': True} 

-3.6488432812686495 



In [21]:
# Precicciones
ypred = gs.best_estimator_.predict(xtest_scal)
ypred

array([5.96759494, 6.03934112, 7.34459198, 3.89326209, 4.07392204,
       6.17817658, 7.23702974, 2.6544078 , 7.5808747 , 4.05645739,
       4.3667152 , 6.10182228, 7.60127901, 2.95434962, 5.15379446,
       7.02760273, 5.30666086, 5.88178477, 6.50265793, 6.02722072])

# Ridge regression

In [177]:
#Estimador
est = Ridge()
lambdas = [-2,-1.9,-1.8,-1.7,-1.5,-1.4,-1.35,-1.3,-1.25,-1.2,-1.1,-1,-0.5,0,0.001,0.0001]
parameters = {'alpha': lambdas}

gs = GridSearchCV(est, param_grid=parameters,refit=True, cv=n_folds, scoring="neg_mean_squared_error")

In [178]:
# Entrenar
gs.fit(xtrain_scal, ytrain)

GridSearchCV(cv=5, error_score=nan,
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [-2, -1.9, -1.8, -1.7, -1.5, -1.4, -1.35,
                                   -1.3, -1.25, -1.2, -1.1, -1, -0.5, 0, 0.001,
                                   0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=0)

In [179]:
print(gs.best_estimator_, "\n")
print(gs.best_params_, "\n")
print(gs.best_score_, "\n")

Ridge(alpha=-1.3, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001) 

{'alpha': -1.3} 

-3.6482535486442083 



In [180]:
#Predicciones 
ypred2 = gs.best_estimator_.predict(xtest_scal)
ypred2

array([5.97937724, 6.0520684 , 7.37451101, 3.87772288, 4.06076234,
       6.19273249, 7.26553205, 2.62255136, 7.61390586, 4.04306766,
       4.35741194, 6.11537251, 7.63457893, 2.92644378, 5.154858  ,
       7.05334662, 5.30973784, 5.89243684, 6.52148766, 6.03978836])

# SVR 

In [181]:
# Estimador
est = SVR(max_iter=25000)
parameters = {'C' : [1000,1500,2000,3000,5000],
              'epsilon' : [0.001, 0.01, 0.1,1, 10,100],
             'gamma':[0.001, 0.01, 0.1,1, 10,100]}


gs = GridSearchCV(est, param_grid=parameters,refit=True,
                  cv=n_folds, scoring="neg_mean_squared_error",
                  verbose=3, n_jobs=3)


In [182]:
# Entrenar
gs.fit(xtrain_scal,ytrain)

Fitting 5 folds for each of 180 candidates, totalling 900 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  28 tasks      | elapsed:    3.0s
[Parallel(n_jobs=3)]: Done 900 out of 900 | elapsed:    8.6s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='scale', kernel='rbf',
                           max_iter=25000, shrinking=True, tol=0.001,
                           verbose=False),
             iid='deprecated', n_jobs=3,
             param_grid={'C': [1000, 1500, 2000, 3000, 5000],
                         'epsilon': [0.001, 0.01, 0.1, 1, 10, 100],
                         'gamma': [0.001, 0.01, 0.1, 1, 10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=3)

In [77]:
print(gs.best_estimator_, "\n")
print(gs.best_params_, "\n")
print(gs.best_score_, "\n")

SVR(C=1500, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1,
    kernel='rbf', max_iter=25000, shrinking=True, tol=0.001, verbose=False) 

{'C': 1500, 'epsilon': 0.1, 'gamma': 1} 

-0.616141202148776 



In [183]:
# Predicciones
ypred3 = gs.best_estimator_.predict(xtest_scal)
ypred3

array([3.21608204, 3.22246867, 7.43640269, 5.17826683, 5.23386201,
       3.34056915, 6.86639221, 0.07712826, 9.26223664, 5.23592223,
       5.02958658, 3.25791468, 9.46771639, 1.99218251, 4.21597442,
       5.99964493, 4.03484689, 3.25217955, 4.12530022, 3.21887533])

# KNN

In [168]:
parameters_k = np.arange(1,11,1)
parameters_k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
parameters_knn = [{'n_neighbors': parameters_k}]

In [185]:
#estimador
for i, weights in enumerate(['uniform', 'distance']):
    est = neighbors.KNeighborsRegressor(n_neighbors, weights=weights)
    gs = GridSearchCV(est, param_grid=parameters_knn,refit=True,
                  cv=n_folds, scoring="neg_mean_squared_error",
                  verbose=3, n_jobs=3)

In [189]:
#Entrenar
gs.fit(xtrain_scal, ytrain)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  50 out of  50 | elapsed:    0.2s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30,
                                           metric='minkowski',
                                           metric_params=None, n_jobs=None,
                                           n_neighbors=5, p=2,
                                           weights='distance'),
             iid='deprecated', n_jobs=3,
             param_grid=[{'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=3)

In [187]:
print(gs.best_estimator_, "\n")
print(gs.best_params_, "\n")
print(gs.best_score_, "\n")

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                    weights='distance') 

{'n_neighbors': 8} 

-0.950113783374178 



In [190]:
#Predicciones
ypred4 = gs.best_estimator_.predict(xtest_scal)
ypred4

array([ 2.92393505,  3.26962092,  7.46609246,  5.3709889 ,  4.97771795,
        3.72960515,  7.17188444,  1.06742847,  9.89531366,  5.1210491 ,
        5.46862087,  3.53654039, 10.10370806,  2.14385093,  4.09004793,
        6.33895138,  5.00254869,  2.94088323,  4.14479879,  3.21830652])